# Default game size
GRID_SIZE = 10
CELL_SIZE = 40
MARGIN = 100
HEIGHT = MARGIN + GRID_SIZE * CELL_SIZE + MARGIN
WIDTH = MARGIN + GRID_SIZE * CELL_SIZE + MARGIN

# Default game settings
SNAKE_SIZE = 3
GREEN_FRUITS_NB = 3
RED_FRUITS_NB = 1

# Game speed
FPS = 5000

R_COLLISION = -20
R_GREEN_FRUIT = 20
R_RED_FRUIT = -5
R_WIN = 100