# Default game size
GRID_SIZE = 10
CELL_SIZE = 40
MARGIN = 100
MIN_AI_WIDTH = 475
MIN_GAME_HEIGHT = 600

GAME_SIZE = GRID_SIZE * CELL_SIZE
HEIGHT = max(MIN_GAME_HEIGHT, MARGIN + GAME_SIZE + MARGIN)
WIDTH = MARGIN + GAME_SIZE + MARGIN + MIN_AI_WIDTH

# Default game settings
SNAKE_SIZE = 3
GREEN_FRUITS_NB = 3
RED_FRUITS_NB = 1

# Game speed
FPS = 15

R_COLLISION = -20
R_GREEN_FRUIT = 20
R_RED_FRUIT = -5
R_WIN = 100
